apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-clone-tekton
spec:
  type: git
  params:
    - name: revision
      value: modify-release-v0.15.x
    - name: url
      value: https://github.com/yyunk/pipeline.git
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-tekton
spec:
  resources:
    inputs:
      - name: task-input-tekton
        type: git
  steps:
    - name: go-build
      image: golang:1.15
      env:
        - name: "PATH"
          value: "/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - name: "GOPATH"
          value: "/go"
      script: |
        #!/usr/bin/env bash
        cd $(resources.inputs.task-input-tekton.path)
        for i in `realpath cmd/*`;
        do
        cd $i; make -f ../../Makefile all;
        done
        cd $(resources.inputs.task-input-tekton.path)
        mkdir -p bin
        for j in `ls cmd`;
        do
        cp cmd/$j/.bin/github.com/tektoncd/pipeline bin/$j;
        done
        cd $(resources.inputs.task-input-tekton.path)/vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher
        go build main.go
        cp main $(resources.inputs.task-input-tekton.path)/bin/gcs-fetcher
        ls $(resources.inputs.task-input-tekton.path)/bin
    - name: build-and-push-images
      image: kaniko:bash
      volumeMounts:
        - name: kaniko-docker-secret
          mountPath: /kaniko/.docker/
      script: |
        #!/bin/bash
        for i in `ls $(resources.inputs.task-input-tekton.path) |grep Dockerfile`
        do
        imagename=`echo  $i|awk -F "." '{print $2}'`
        /kaniko/executor --dockerfile=$(resources.inputs.task-input-tekton.path)/$i \
         --insecure-registry=213.146.155.118:5500 \
         --registry-mirror=213.146.155.118:5500 \
         --skip-tls-verify-registry=213.146.155.118:5500 \
         --context=dir:///$(resources.inputs.task-input-tekton.path) \
         --destination=213.146.155.118:5500/tekton-$imagename:0.15.2 \
         --skip-tls-verify \
         --skip-tls-verify-pull
        done
  volumes:
    - name: kaniko-docker-secret
      hostPath:
        path: /home/ubuntu/docker-config/
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: task-tekton-pipeline
spec:
  resources:
    - name: tekton-pipeline-input-1
      type: git
  tasks:
    - name: step1
      taskRef:
        name: task-tekton
      resources:
        inputs:
          - name: task-input-tekton
            resource: tekton-pipeline-input-1
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-tekton
spec:
  serviceAccountName: tutorial-service
  pipelineRef:
    name: task-tekton-pipeline
  resources:
    - name: tekton-pipeline-input-1
      resourceRef:
        name: git-clone-tekton
